version: '3'

services:
  php:
    container_name: symfony-php
    build: ./.docker/php
    depends_on:
      - pgsql
    volumes:
      - ./:/usr/src/app
    user: 1000:1000
#    ports:
#      - "80:80"
    environment:
      APP_ENV: dev
      DATABASE_URL: "postgres://postgresql:postgresql@pgsql:5432/glaubensfutter"
    networks:
      symfony-network:
        ipv4_address: 10.201.0.3
  nginx:
    image: nginx:1.15.3-alpine
#    restart: on-failure
    depends_on:
      - php
    volumes:
      - './public:/usr/src/app'
      - './.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - "80:80"
    networks:
      symfony-network:
        ipv4_address: 10.201.0.6

  pgsql:
    container_name: symfony-pgsql
    build: ./.docker/db
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: postgresql
    networks:
      symfony-network:
        ipv4_address: 10.201.0.4
networks:
  symfony-network:
    driver: bridge
    ipam:
      config:
        - subnet: "10.201.0.0/24"


# Hosts
